#   A basic travis.yml boilerplate for Django projects

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.9.6

before_install:
  - export DJANGO_SETTINGS_MODULE=ActivitySync.settings
  - export PYTHONPATH=$HOME/builds/FreexD/ActivitySyncDjango
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput