# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160608_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='description',
        ),
    ]
