# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160608_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.IntegerField(default=0),
        ),
    ]
