# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('event', '0004_event_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='discipline.Discipline'),
            preserve_default=False,
        ),
    ]
